export const banks = [
  { code: '', text: 'Không chọn' },
  { code: 'MBAPP', text: 'Ứng dụng MobileBanking' },
  { code: 'VNPAYQR', text: 'VNPAYQR' },
  { code: 'VNBANK', text: 'LOCAL BANKING' },
  { code: 'IB', text: 'INTERNET BANKING' },
  { code: 'ATM', text: 'ATM CAR' },
  { code: 'INTCARD', text: 'INTERNATIONAL CAR' },
  { code: 'VISA', text: 'VIS' },
  { code: 'MASTERCARD', text: ' MASTERCAR' },
  { code: 'JCB', text: 'JC' },
  { code: 'UPI', text: 'UP' },
  { code: 'VIB', text: 'VI' },
  { code: 'VIETCAPITALBANK', text: 'VIETCAPITALBANK' },
  { code: 'SCB', text: 'Ngân hàng SCB' },
  { code: 'NCB', text: 'Ngân hàng NCB' },
  { code: 'SACOMBANK', text: 'Ngân hàng SacomBank' },
  { code: 'EXIMBANK', text: 'Ngân hàng EximBank' },
  { code: 'MSBANK', text: 'Ngân hàng MSBANK' },
  { code: 'NAMABANK', text: 'Ngân hàng NamABank' },
  { code: 'VNMART', text: ' Ví điện tử VnMar' },
  { code: 'VIETINBANK', text: 'Ngân hàng Vietinbank' },
  { code: 'VIETCOMBANK', text: 'Ngân hàng VCB' },
  { code: 'HDBANK', text: 'Ngân hàng HDBank' },
  { code: 'DONGABANK', text: 'Ngân hàng Dong ' },
  { code: 'TPBANK', text: 'Ngân hàng TPBank' },
  { code: 'OJB', text: 'Ngân hàng OceanBan' },
  { code: 'BIDV', text: 'Ngân hàng BIDV' },
  { code: 'TECHCOMBANK', text: 'Ngân hàng Techcombank' },
  { code: 'VPBANK', text: 'Ngân hàng VPBank' },
  { code: 'AGRIBANK', text: 'Ngân hàng Agribank' },
  { code: 'MBBANK', text: 'Ngân hàng MBBank' },
  { code: 'ACB', text: 'Ngân hàng ACB' },
  { code: 'OCB', text: 'Ngân hàng OCB' },
  { code: 'IVB', text: 'Ngân hàng IVB' },
  { code: 'SHB', text: 'Ngân hàng SHB' }
];
